[package]
name = "gamma_setter_core"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Graphics_Gdi", 
    "Win32_UI_ColorSystem"
] }

[lib]
crate-type = ["cdylib"]